### ISSUE TITLE
Setup Data Logging Pipeline

### ISSUE THREAD

**Issue by achung123** [achung123/ROM_Rehab_Control#3]
There are different libraries that allow python scripts to interface with CSV files. Initially focus can be placed on sending data to a CSV file and plotting it afterward. It would be nice if we could read data from the sensors and plot it in real time during the exercise. This will be especially helpful during the debugging and fine tuning phase of control algorithms and parameters. This can also be done  through a library that allows python to interface with the Serial output of the Arduino. Plotting can be done with matplotlib. Some good reach goals can be embedding plots inside of interactive GUI that takes in input for ROM, speed, and reps. 

Below is an example of communicating with the Arduino: 
https://www.google.com/amp/s/toptechboy.com/python-with-arduino-lesson-11-plotting-and-graphing-live-data-from-arduino-with-matplotlib/

Below is an example of plotting live data: 
https://github.com/makerportal/pylive.git

Lastly, below is an example of embedding plots inside of tkinter gui's: 
https://www.youtube.com/watch?v=8exB6Ly3nx0

**Comment by ashleyl1** [comment]
Current working files: basic live plotting graph based on DHTsensor (only thing I have at the moment)

Currently: Working on integrating the live plotting graph into Tkinter so we can make it interactive.

Wednesday: getting the SD card module and can implement the data storage pipeline. Found this website that could be useful: [Writing CSV files to SD card](https://rydepier.wordpress.com/2015/08/07/using-an-sd-card-reader-to-store-and-retrieve-data-with-arduino/)
